name: churchdata_core_mocks
description: core library mocks for churchdata_core
version: 0.5.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.8.1"

dependency_overrides:
  firebase_core: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  churchdata_core:
    git:
      url: https://github.com/Andrew-Bekhiet/churchdata_core
      ref: master
  mockito: ^5.4.3
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.2
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  fake_cloud_firestore: ^3.0.1
  firebase_auth_mocks: ^0.14.0
  firebase_storage_mocks: ^0.7.0
  firebase_database_mocks: ^0.6.1
  google_sign_in_mocks: ^0.3.0
  network_image_mock: ^2.1.1
  mock_data: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
