name: churchdata_core_mocks
description: core library mocks for churchdata_core
version: 0.2.0
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  churchdata_core:
    git:
      url: https://github.com/Andrew-Bekhiet/churchdata_core
      ref: master
  flutter_lints: ^1.0.4
  mockito: ^5.1.0
  build_runner: ^2.1.7
  copy_with_extension_gen: ^4.0.1
  hive_generator: ^1.1.2
  hive_test: ^1.0.1
  fake_cloud_firestore: ^1.2.2
  firebase_storage_mocks: ^0.5.1
  firebase_auth_mocks: ^0.8.2
  firebase_database_mocks:
    git:
      url: https://github.com/OlegNovosad/firebase_database_mocks
      ref: main
  google_sign_in_mocks: ^0.2.1
  network_image_mock: ^2.0.1
  mock_data: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
